name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v4

    - id: setup-bun
      name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - id: install-dependencies
      name: Install dependencies
      run: |
        bun install

    - id: turbo-telemetry
      name: Turbo telemetry
      run: |
        bunx turbo telemetry status
        bunx turbo telemetry disable

    - id: setup-git
      name: Setup Git
      run: |
        git config user.name "$GIT_USER_NAME"
        git config user.email "$GIT_USER_EMAIL"
      env:
        GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}

    - id: release
      name: Release
      run: bun run release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
